nodeLinker: node-modules

npmRegistryServer: "https://artifacts.na.c-gurus.com/artifactory/api/npm/npm-registry"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
