name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  call-workflow-passing-data:
    uses: cargurus-eng/reusable-github-actions/.github/workflows/code-coverage.yml@main
    with:
      SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
      SONAR_PROJECT_KEY: ${{ github.event.repository.name }}
    secrets: inherit
